### ISSUE TITLE
Chromosome names require leading "chr"

### ISSUE THREAD

**Issue by robertamezquita** [shawnzhangyx/PePr#22]
In using the Ensembl reference for alignment, which only uses numbers + X/Y for chromosomes, it seems that in the prepare_data_peak_calling routine, that the program is crashing on the first read when there is no leading "chr".  Here's the relevant traceback:

```
INFO   root 07/26/2016 01:36:15 PM | Begin peak-calling
Traceback (most recent call last):
  File "/home/ra364/.local/bin/PePr", line 11, in <module>
    sys.exit(argless_main())
  File "/home/ra364/.local/lib/python2.7/site-packages/PePr/PePr.py", line 27, in argless_main
SDIRmain(sys.argv)
PRFile "/home/ra364/.local/lib/python2.7/site-packages/PePr/PePr.py", line 42, in main
    read_dict = prepareData.prepare_data(parameter)
  File "/home/ra364/.local/lib/python2.7/site-packages/PePr/prepareData.py", line 261, in prepare_data
    read_dict = prepare_data_peak_calling(parameter)
  File "/home/ra364/.local/lib/python2.7/site-packages/PePr/prepareData.py", line 173, in prepare_data_peak_calling
    data_dict[chr] = numpy.column_stack((data_dict[chr], parameter.array_dict[filename][chr]))
KeyError: '1'
```

**Comment by shawnzhangyx** [comment]
If all files are processed in the same way, it does not matter what the chromosome name is, as long as it is consistent. Are ChIP file and input files processed differently?
