### ISSUE TITLE
libhts.so.1 import error

### ISSUE THREAD

**Issue by abalter** [shawnzhangyx/PePr#25]
I tried installing both with pip and conda, and both with python 3 and python 2. I get this same error.

```
balter@:/mnt/scratch/bcore/balter$ conda install pepr
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/Applications/conda:

The following NEW packages will be INSTALLED:

    pepr: 1.1.18-py35_0 bioconda

Proceed ([y]/n)? y

balter@:/mnt/scratch/bcore/balter$ PePr -h
Traceback (most recent call last):
  File "/home/Applications/conda/bin/PePr", line 4, in <module>
    import PePr.PePr
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/PePr.py", line 12, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/optParser.py", line 3, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/classDef.py", line 4, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
balter@:/mnt/scratch/bcore/balter$ PePr --version
Traceback (most recent call last):
  File "/home/Applications/conda/bin/PePr", line 4, in <module>
    import PePr.PePr
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/PePr.py", line 12, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/optParser.py", line 3, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/classDef.py", line 4, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory 
```

**Comment by abalter** [comment]
Ok, here's how I fixed it. I did `conda update pysam` which asked me to downgrade `bcftools`, `htslib` and a couple of other packages. After doing that, `PePr` seems to work. After I was able to upgrade bcftools again. and it still sees to work. 

I wish I could tell you all the packages, but I was working in a screen session which doesn't scroll. Not quite sure what I could do to reproduce.

**Comment by abalter** [comment]
Ok, I was able to reproduce:

```
balter:/mnt/scratch/bcore$ PePr -h
Usage: Basic usage: PePr -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess

Options:
  -h, --help            show this help message and exit
  -p PARAMETER-FILE, --parameter-file=PARAMETER-FILE
                        provide a file that contain the parameters
  -c CHIP1, --chip1=CHIP1
                        chip1 file names separated by comma
  -i INPUT1, --input1=INPUT1
                        input1 file names separated by comma
  --chip2=CHIP2         chip2 file names separated by comma
  --input2=INPUT2       input2 file names separated by comma
  -f FORMAT, --file-format=FORMAT
                        bed, sam, bam, sampe, bampe...
  -s SHIFTSIZE, --shiftsize=SHIFTSIZE
                        Half the fragment size.
  -w WINDOWSIZE, --windowsize=WINDOWSIZE
                        Window sizes
  --diff                Perform differential binding instead of peak-calling
  -n NAME, --name=NAME  the experimental name. NA if none provided
  --threshold=THRESHOLD
                        p-value threshold. Default 1e-5.
  --peaktype=PEAKTYPE   sharp or broad. Default broad.
  --num-processors=NUM_PROCS
                        number of cores for use.
  --input-directory=INPUT_DIRECTORY
                        where the data files are. Absolute path recommended.
  --output-directory=OUTPUT_DIRECTORY
                        where you want the output files to be
  --normalization=NORMALIZATION
                        Normalization method. inter-group, intra-group, scale
                        or no. Must manually specify for differential binding
                        analysis.
  --keep-max-dup=KEEP_MAX_DUP
                        maximum number of reads to keep at each position.
                        if not specified, will not remove any duplicate.
  --version             Show version information and exit
balter:/mnt/scratch/bcore$ conda update bcftools
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/Applications/conda:

The following packages will be UPDATED:

    bcftools: 1.3.1-1       bioconda --> 1.4-0         bioconda

The following packages will be DOWNGRADED due to dependency conflicts:

    pysam:    0.10.0-py35_3 bioconda --> 0.10.0-py35_2 bioconda

Proceed ([y]/n)? y

balter:/mnt/scratch/bcore$ PePr -h
-bash: /home/Applications/conda/bin/PePr: Permission denied
balter:/mnt/scratch/bcore$ conda install PePr
-bash: /home/Applications/conda/bin/conda: Permission denied
balter:/mnt/scratch/bcore$ PePr -h
Usage: Basic usage: PePr -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess

Options:
  -h, --help            show this help message and exit
  -p PARAMETER-FILE, --parameter-file=PARAMETER-FILE
                        provide a file that contain the parameters
  -c CHIP1, --chip1=CHIP1
                        chip1 file names separated by comma
  -i INPUT1, --input1=INPUT1
                        input1 file names separated by comma
  --chip2=CHIP2         chip2 file names separated by comma
  --input2=INPUT2       input2 file names separated by comma
  -f FORMAT, --file-format=FORMAT
                        bed, sam, bam, sampe, bampe...
  -s SHIFTSIZE, --shiftsize=SHIFTSIZE
                        Half the fragment size.
  -w WINDOWSIZE, --windowsize=WINDOWSIZE
                        Window sizes
  --diff                Perform differential binding instead of peak-calling
  -n NAME, --name=NAME  the experimental name. NA if none provided
  --threshold=THRESHOLD
                        p-value threshold. Default 1e-5.
  --peaktype=PEAKTYPE   sharp or broad. Default broad.
  --num-processors=NUM_PROCS
                        number of cores for use.
  --input-directory=INPUT_DIRECTORY
                        where the data files are. Absolute path recommended.
  --output-directory=OUTPUT_DIRECTORY
                        where you want the output files to be
  --normalization=NORMALIZATION
                        Normalization method. inter-group, intra-group, scale
                        or no. Must manually specify for differential binding
                        analysis.
  --keep-max-dup=KEEP_MAX_DUP
                        maximum number of reads to keep at each position.
                        if not specified, will not remove any duplicate.
  --version             Show version information and exit
balter:/mnt/scratch/bcore$ conda list | grep hst
balter:/mnt/scratch/bcore$ conda list | grep hts
htslib                    1.3.2                         0    bioconda
balter:/mnt/scratch/bcore$ conda update htslib
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/Applications/conda:

The following packages will be UPDATED:

    htslib: 1.3.2-0 bioconda --> 1.4-0 bioconda

Proceed ([y]/n)? y

balter:/mnt/scratch/bcore$ PePr -h
Traceback (most recent call last):
  File "/home/Applications/conda/bin/PePr", line 4, in <module>
    import PePr.PePr
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/PePr.py", line 12, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/optParser.py", line 3, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/classDef.py", line 4, in <module>
  File "/home/Applications/conda/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

**Comment by abalter** [comment]
Aha. Here is a clean reproduction:

```
balter3:~$ conda create --name pepr pepr
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/Applications/conda/envs/pepr:

The following NEW packages will be INSTALLED:

    bcftools:    1.4-0              bioconda
    bzip2:       1.0.6-3            anaconda
    curl:        7.52.1-0           anaconda
    htslib:      1.4-0              bioconda
    libgcc:      5.2.0-0            anaconda
    libgfortran: 3.0.0-1            anaconda
    mkl:         2017.0.1-0         anaconda
    numpy:       1.12.1-py35_0      anaconda
    openssl:     1.0.2k-1           anaconda
    pepr:        1.1.18-py35_0      bioconda
    pip:         9.0.1-py35_1       anaconda
    pysam:       0.10.0-py35_2      bioconda
    python:      3.5.3-1            anaconda
    readline:    6.2-2              anaconda
    samtools:    1.4-0              bioconda
    scipy:       0.19.0-np112py35_0 anaconda
    setuptools:  27.2.0-py35_0      anaconda
    sharedmem:   0.3.5-py35_0       bioconda
    sqlite:      3.13.0-0           anaconda
    tk:          8.5.18-0           anaconda
    wheel:       0.29.0-py35_0      anaconda
    xz:          5.2.2-1            anaconda
    zlib:        1.2.8-3            anaconda

Proceed ([y]/n)? y

python-3.5.3-1 100% |###########################################################################################################################################################################################| Time: 0:00:02   5.67 MB/s
#
# To activate this environment, use:
# > source activate pepr
#
# To deactivate this environment, use:
# > source deactivate pepr
#

balter3:~$ source activate pepr
(pepr) balter3:~$ PePr -h
Traceback (most recent call last):
  File "/home/Applications/conda/envs/pepr/bin/PePr", line 4, in <module>
    import PePr.PePr
  File "/home/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/PePr.py", line 12, in <module>
  File "/home/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/optParser.py", line 3, in <module>
  File "/home/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/classDef.py", line 4, in <module>
  File "/home/Applications/conda/envs/pepr/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

**Comment by abalter** [comment]
It definitely appears to be some conflict between `pysam 0.10.0-py35_3` and `bcftools: 1.4-0`.

Probably should be posted as an issue with one of those. Any suggestions for which one?

```
(pepr) balter@exalab3:~$ conda update pysam
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr:

The following packages will be UPDATED:

    pysam:    0.10.0-py35_2 bioconda --> 0.10.0-py35_3 bioconda

The following packages will be DOWNGRADED due to dependency conflicts:

    bcftools: 1.4-0         bioconda --> 1.3.1-1       bioconda
    htslib:   1.4-0         bioconda --> 1.3.2-0       bioconda
    samtools: 1.4-0         bioconda --> 1.3.1-5       bioconda

Proceed ([y]/n)? y

(pepr) balter@exalab3:~$ PePr -h
Usage: Basic usage: PePr -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess

Options:
  -h, --help            show this help message and exit
  -p PARAMETER-FILE, --parameter-file=PARAMETER-FILE
                        provide a file that contain the parameters
  -c CHIP1, --chip1=CHIP1
                        chip1 file names separated by comma
  -i INPUT1, --input1=INPUT1
                        input1 file names separated by comma
  --chip2=CHIP2         chip2 file names separated by comma
  --input2=INPUT2       input2 file names separated by comma
  -f FORMAT, --file-format=FORMAT
                        bed, sam, bam, sampe, bampe...
  -s SHIFTSIZE, --shiftsize=SHIFTSIZE
                        Half the fragment size.
  -w WINDOWSIZE, --windowsize=WINDOWSIZE
                        Window sizes
  --diff                Perform differential binding instead of peak-calling
  -n NAME, --name=NAME  the experimental name. NA if none provided
  --threshold=THRESHOLD
                        p-value threshold. Default 1e-5.
  --peaktype=PEAKTYPE   sharp or broad. Default broad.
  --num-processors=NUM_PROCS
                        number of cores for use.
  --input-directory=INPUT_DIRECTORY
                        where the data files are. Absolute path recommended.
  --output-directory=OUTPUT_DIRECTORY
                        where you want the output files to be
  --normalization=NORMALIZATION
                        Normalization method. inter-group, intra-group, scale
                        or no. Must manually specify for differential binding
                        analysis.
  --keep-max-dup=KEEP_MAX_DUP
                        maximum number of reads to keep at each position.
                        if not specified, will not remove any duplicate.
  --version             Show version information and exit
(pepr) balter@exalab3:~$ conda update bcftools
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr:

The following packages will be UPDATED:

    bcftools: 1.3.1-1       bioconda --> 1.4-0         bioconda

The following packages will be DOWNGRADED due to dependency conflicts:

    pysam:    0.10.0-py35_3 bioconda --> 0.10.0-py35_2 bioconda

Proceed ([y]/n)? y

(pepr) balter@exalab3:~$ PePr -h
Usage: Basic usage: PePr -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess

Options:
  -h, --help            show this help message and exit
  -p PARAMETER-FILE, --parameter-file=PARAMETER-FILE
                        provide a file that contain the parameters
  -c CHIP1, --chip1=CHIP1
                        chip1 file names separated by comma
  -i INPUT1, --input1=INPUT1
                        input1 file names separated by comma
  --chip2=CHIP2         chip2 file names separated by comma
  --input2=INPUT2       input2 file names separated by comma
  -f FORMAT, --file-format=FORMAT
                        bed, sam, bam, sampe, bampe...
  -s SHIFTSIZE, --shiftsize=SHIFTSIZE
                        Half the fragment size.
  -w WINDOWSIZE, --windowsize=WINDOWSIZE
                        Window sizes
  --diff                Perform differential binding instead of peak-calling
  -n NAME, --name=NAME  the experimental name. NA if none provided
  --threshold=THRESHOLD
                        p-value threshold. Default 1e-5.
  --peaktype=PEAKTYPE   sharp or broad. Default broad.
  --num-processors=NUM_PROCS
                        number of cores for use.
  --input-directory=INPUT_DIRECTORY
                        where the data files are. Absolute path recommended.
  --output-directory=OUTPUT_DIRECTORY
                        where you want the output files to be
  --normalization=NORMALIZATION
                        Normalization method. inter-group, intra-group, scale
                        or no. Must manually specify for differential binding
                        analysis.
  --keep-max-dup=KEEP_MAX_DUP
                        maximum number of reads to keep at each position.
                        if not specified, will not remove any duplicate.
  --version             Show version information and exit
(pepr) balter@exalab3:~$ conda update htslib samtools
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr:

The following packages will be UPDATED:

    htslib:   1.3.2-0 bioconda --> 1.4-0 bioconda
    samtools: 1.3.1-5 bioconda --> 1.4-0 bioconda

Proceed ([y]/n)? y

(pepr) balter@exalab3:~$ PePr -h
Traceback (most recent call last):
  File "/home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr/bin/PePr", line 4, in <module>
    import PePr.PePr
  File "/home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/PePr.py", line 12, in <module>
  File "/home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/optParser.py", line 3, in <module>
  File "/home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr/lib/python3.5/site-packages/PePr-1.1.18-py3.5.egg/PePr/classDef.py", line 4, in <module>
  File "/home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
(pepr) balter@exalab3:~$ conda update pysam
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/exacloud/lustre1/BioCoders/Applications/conda/envs/pepr:

The following packages will be UPDATED:

    pysam:    0.10.0-py35_2 bioconda --> 0.10.0-py35_3 bioconda

The following packages will be DOWNGRADED due to dependency conflicts:

    bcftools: 1.4-0         bioconda --> 1.3.1-1       bioconda
    htslib:   1.4-0         bioconda --> 1.3.2-0       bioconda
    samtools: 1.4-0         bioconda --> 1.3.1-5       bioconda

Proceed ([y]/n)? y

(pepr) balter@exalab3:~$ PePr -h
Usage: Basic usage: PePr -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess

Options:
  -h, --help            show this help message and exit
  -p PARAMETER-FILE, --parameter-file=PARAMETER-FILE
                        provide a file that contain the parameters
  -c CHIP1, --chip1=CHIP1
                        chip1 file names separated by comma
  -i INPUT1, --input1=INPUT1
                        input1 file names separated by comma
  --chip2=CHIP2         chip2 file names separated by comma
  --input2=INPUT2       input2 file names separated by comma
  -f FORMAT, --file-format=FORMAT
                        bed, sam, bam, sampe, bampe...
  -s SHIFTSIZE, --shiftsize=SHIFTSIZE
                        Half the fragment size.
  -w WINDOWSIZE, --windowsize=WINDOWSIZE
                        Window sizes
  --diff                Perform differential binding instead of peak-calling
  -n NAME, --name=NAME  the experimental name. NA if none provided
  --threshold=THRESHOLD
                        p-value threshold. Default 1e-5.
  --peaktype=PEAKTYPE   sharp or broad. Default broad.
  --num-processors=NUM_PROCS
                        number of cores for use.
  --input-directory=INPUT_DIRECTORY
                        where the data files are. Absolute path recommended.
  --output-directory=OUTPUT_DIRECTORY
                        where you want the output files to be
  --normalization=NORMALIZATION
                        Normalization method. inter-group, intra-group, scale
                        or no. Must manually specify for differential binding
                        analysis.
  --keep-max-dup=KEEP_MAX_DUP
                        maximum number of reads to keep at each position.
                        if not specified, will not remove any duplicate.
  --version             Show version information and exit
```

**Comment by shawnzhangyx** [comment]
Thanks for reporting this. PePr is depending on the pysam package to access BAM files. And pysam seems to have some version issues with htslib. When you update htslib, it will break. I've seen this issue before, but I am not sure if they will try to fix it with the new version of htslib. 
See this: https://pysam.readthedocs.io/en/latest/ 

> The current version wraps htslib-1.3, samtools-1.3 and bcftools-1.3.
