### ISSUE TITLE
KeyError in post_process_PePr.py

### ISSUE THREAD

**Issue by alacrity8** [shawnzhangyx/PePr#27]
Hi,

I have encountered a KeyError while running PePr-postprocess (traceback is shown below). I think it may be due to lack of forward or reverse-strand alignments for certain contigs (e.g. in cases where single-end ChIP-seq was used). Is there a way to recover from this error, such as leave the current peak as it is and let the post-processing move on to the next peak?

Traceback (most recent call last):
  File "/home/alison/bin/PePr-postprocess", line 9, in <module>
    load_entry_point('PePr==1.1.18', 'console_scripts', 'PePr-postprocess')()
  File "/home/alison/lib/python2.7/site-packages/PePr/post_processing/post_process_PePr.py", line 265, in post_processing_module
    main(sys.argv)
  File "/home/alison/lib/python2.7/site-packages/PePr/post_processing/post_process_PePr.py", line 117, in main
    post_processing(readData,file_in,file_passed,file_failed, opt.remove_artefacts, opt.narrow_peak)
  File "/home/alison/lib/python2.7/site-packages/PePr/post_processing/post_process_PePr.py", line 137, in post_processing
    narrow_peak, remove_artefacts)
  File "/home/alison/lib/python2.7/site-packages/PePr/post_processing/post_process_PePr.py", line 190, in post_processing_per_peak
    forward = strands_dict[input][chr]['f']
KeyError: '<contig>'

Thank you for reviewing this issue.
-A

**Comment by shawnzhangyx** [comment]
Thank you for you comments. It seems like there is a key with zero-length string. Could you paste the command that you ran and the log files for the peak calls?

**Comment by alacrity8** [comment]
Thanks for the quick response!
The key in my first post was a non-empty string. The traceback appears as such as I left out the contig name. 
In an attempt to solve this issue, I added statements to catch the KeyError exception in post_process_PePr.py and the program runs to completion now.

**Comment by shawnzhangyx** [comment]
No problem. Glad you fixed it!
